const $=s=>document.querySelector(s);
const state={market:"new",offers:[],meta:null};
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function uniq(v){return [...new Set(v.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"ko"))}
function setOptions(el,vals,label){const cur=el.value;el.innerHTML='<option value="">'+label+'</option>'+vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join("");if([...el.options].some(x=>x.value===cur))el.value=cur}
function priceLabel(o){const t=o.price?.price_type;const prefix=t==="manufacturer_msrp"?"공식가격":t==="listing_price"?"매물가":"참고시세";return prefix+" "+Number(o.price?.amount_krw||0).toLocaleString("ko-KR")+"원"}
function rebuild(){const rows=state.offers.filter(x=>x.market===state.market);setOptions($("#purchaseMaker"),uniq(rows.map(x=>x.maker)),"제조사 전체");setOptions($("#purchaseYear"),uniq(rows.map(x=>x.vehicle_ref?.model_year).filter(Boolean)),"연식 전체")}
function render(){let rows=state.offers.filter(x=>x.market===state.market);if($("#purchaseMaker").value)rows=rows.filter(x=>x.maker===$("#purchaseMaker").value);if($("#purchaseYear").value)rows=rows.filter(x=>String(x.vehicle_ref?.model_year)===String($("#purchaseYear").value));const sort=$("#purchaseSort").value;rows.sort((a,b)=>sort==="priceDesc"?(b.price.amount_krw-a.price.amount_krw):sort==="recent"?String(b.observed_at).localeCompare(String(a.observed_at)):(a.price.amount_krw-b.price.amount_krw));const root=$("#purchaseResults");if(!state.offers.length){$("#purchaseMeta").textContent="실데이터 연동 준비 중";root.innerHTML='<div class="purchase-empty"><strong>검증된 차량 구매 데이터 연결 준비 중</strong><p>신차 공식가격과 중고차 매물가·참고시세를 분리해 수집합니다. 아직 검증된 데이터가 없으므로 예시 가격을 만들지 않습니다.</p></div>';return}$("#purchaseMeta").textContent=rows.length+"건";root.innerHTML=rows.length?rows.map(o=>'<article class="purchase-card"><div class="purchase-card-top"><span class="pill">'+(o.market==="new"?"신차":"중고차")+'</span><span class="purchase-price">'+esc(priceLabel(o))+'</span></div><h3>'+esc(o.maker+" "+o.model)+'</h3><div class="meta">'+esc((o.vehicle_ref?.model_year||"연식 확인 중")+(o.vehicle_ref?.trim?" · "+o.vehicle_ref.trim:""))+'</div><p>'+esc(o.summary||"상세 조건 검증 중")+'</p><div class="purchase-links"><span>카드: '+esc(o.card_status||"연결 준비 중")+'</span><span>대출: '+esc(o.finance_status||"연결 준비 중")+'</span></div></article>').join(""):'<div class="purchase-empty">선택한 조건에 맞는 검증된 구매 데이터가 없습니다.</div>'}
Promise.all([fetch("../data/purchase/offers.json?v=20261010c").then(r=>r.ok?r.json():Promise.reject()),fetch("../data/purchase/meta.json?v=20261010c").then(r=>r.ok?r.json():Promise.reject())]).then(([offers,meta])=>{state.offers=Array.isArray(offers)?offers:[];state.meta=meta;rebuild();render()}).catch(()=>{$("#purchaseResults").innerHTML='<div class="purchase-empty">차량 구매 데이터를 불러오지 못했습니다.</div>'});
document.querySelectorAll("#purchaseTabs .tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("#purchaseTabs .tab").forEach(x=>x.classList.remove("is-active"));btn.classList.add("is-active");state.market=btn.dataset.market;$("#purchaseMaker").value="";$("#purchaseYear").value="";rebuild();render()}));["purchaseMaker","purchaseYear","purchaseSort"].forEach(id=>$("#"+id).addEventListener("change",render));